language: python
python: 2.7
env:
  global:
    LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
  matrix:
    - TOXENV=check
    - TOXENV=2.6-paste,coveralls
    - TOXENV=2.6-paste-nocover
    - TOXENV=2.7-paste,coveralls
    - TOXENV=2.7-paste-nocover
    - TOXENV=3.2,coveralls
    - TOXENV=3.2-nocover
    - TOXENV=3.3,coveralls
    - TOXENV=3.3-nocover
    - TOXENV=3.4,coveralls
    - TOXENV=3.4-nocover
    - TOXENV=pypy-paste,coveralls
    - TOXENV=pypy-paste-nocover
before_install:
  - python --version
  - virtualenv --version
  - pip --version
  - uname -a
  - lsb_release -a
install:
  - pip install tox
script:
  - tox -v
notifications:
  email:
    on_success: never
    on_failure: always

